import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
	ButtonModule,
	CheckboxModule,
	DropdownModule,
	FileUploaderModule,
	GridModule,
	InputModule,
	ListModule,
	RadioModule,
	SearchModule,
	SelectModule,
	TabsModule,
	TilesModule,
	ModalModule,
	ModalService,
	PlaceholderModule,
	DocumentationModule,
	DialogModule,
	NotificationModule,
	NotificationService,
	NumberModule,
	LoadingModule,
	AccordionModule,
	TableModule,
	DatePickerModule,
	ComboBoxModule
} from "carbon-components-angular";
@NgModule({
	declarations: [],
	imports: [
		CommonModule,
		ButtonModule,
		CheckboxModule,
		DropdownModule,
		FileUploaderModule,
		GridModule,
		NumberModule,
		InputModule,
		RadioModule,
		SearchModule,
		SelectModule,
		TabsModule,
		TilesModule,
		ModalModule,
		PlaceholderModule,
		DocumentationModule,
		DialogModule,
		NotificationModule,
		AccordionModule,
		LoadingModule,
		TableModule,
		DatePickerModule,
		ComboBoxModule
	],
	providers: [ModalService, NotificationService],
	exports: [
		ButtonModule,
		CheckboxModule,
		DropdownModule,
		FileUploaderModule,
		GridModule,
		NumberModule,
		InputModule,
		RadioModule,
		SearchModule,
		SelectModule,
		TabsModule,
		ListModule,
		TilesModule,
		ModalModule,
		PlaceholderModule,
		DocumentationModule,
		DialogModule,
		NotificationModule,
		LoadingModule,
		TableModule,
		AccordionModule,
		DatePickerModule,
		ComboBoxModule
	]
})
export class CarbonModule {}
